### ISSUE TITLE
Request: Multiple Manga Download / Download Queue

### ISSUE THREAD

**Issue by shull49** [ErisLoona/Manga-Library-Manager#3]
When I am downloading a manga the download screen stays active.  It is not clear if I can close it and start another download or not.
It would be great if I could queue up a bunch of downloads and let them run in the background.

**Comment by ErisLoona** [comment]
Deployed in the [v3.0](https://github.com/ErisLoona/Manga-Library-Manager/releases) with the Avalonia rewrite. If you encounter any issues with it please let me know.  

Thank you for using my program, hope you enjoy ^-^
